[project]
name = "hailo-installation"
version = "0.1.0"
description = "Installation and setup logic"
authors = [{ name = "Hailo" }]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
