[project]
name = "hailo-gstreamer"
version = "0.1.0"
description = "GStreamer interface"
authors = [{ name = "Omriz" }]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
