hailort_version: "4.20.0"
tappas_version: "3.31.0"
apps_infra_version: "25.3.1"
model_zoo_version: "v2.14.0"
device_arch: "auto" # Options: "rpi" (Raspberry Pi), "x86" (desktop/server), "arm" (generic ARM board) or "auto" (detect from device)
hailo_arch: "auto" # Options: "hailo8", "hailo8l", or "auto" (detect from device)
resources_path: "/usr/local/hailo/resources" # If set to "auto" or empty, defaults to /usr/local/hailo/resources
virtual_env_name: "hailo_infra_venv" # Name of the virtual environment to be created IF SET TO AUTO OR empty this will default to /usr/local/hailo/resources
server_url: "http://dev-public.hailo.ai/2025_01" # URL of the server to download models from , This is static 
deb_whl_dir: "hailo_temp_resources" # Directory to store the deb and whl files , this is the default if set to auot or empty 
tappas_variant: "tappas" # Options : "tappas" or " tappa-core" or "None"