[project]
name = "hailo-common"
version = "0.1.0"
description = "Shared utilities for Hailo apps"
authors = [{ name = "Omriz" }]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
